name: .NET Core

on: 
  push:
    branches: 
    - master
    - dev

jobs:
  build_upload:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.100
      - name: Setup Python
        uses: actions/setup-python@v1.2.0
        with:
          python-version:: 3.7.4
      - name: Pip install cos-python
        run: pip install -U cos-python-sdk-v5
      - name: Publish
        run: |
          ls
          New-Item -Path . -Name "THUAI3.0" -ItemType "directory"
          ls
          cd ./logic
          ls
          ./build_logic.ps1 -Dir ../THUAI3.0
          cd ..
          # python ./download_windows_only.py --id ${{ secrets.TENCENT_DOWNLOAD_ID }} --key ${{ secrets.TNCENT_DOWNLOAD_KEY }}
          python ./upload_to_tencent_cloud.py --id ${{ secrets.TENCENT_UPLOAD_ID }} --key ${{ secrets.TENCENT_UPLOAD_KEY }} CAPI THUAI3.0 Config runServer.bat runAgent.bat runClientConsole.bat API.md README.md
  deploy:
    runs-on: ubuntu-latest
#     needs: build
    steps:
      - uses: actions/checkout@v1
      - name: Log in to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.100
      - name: Publish server
        run: dotnet publish "logic/Logic.Server/Logic.Server.csproj" -c Release -r linux-x64 --self-contained true
      - name: Publish agent
        run: dotnet publish "communication/Agent/Communication.Agent.csproj" -c Release -r linux-x64 -f netcoreapp3.0 --self-contained true
      - name: Build docker image of server
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/thuai_server:latest -f logic/ServerDockerfile .
      - name: Build docker image of agent
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/thuai_agent:latest -f logic/AgentDockerfile .
      - name: Build CAPI_compile docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/thuai_compiler:latest -f CAPI/Dockerfile_compile .
      - name: Build CAPI_run docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/thuai_client:latest -f CAPI/Dockerfile_run .
      - name: Push server image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/thuai_server:latest
      - name: Push agent image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/thuai_agent:latest
      - name: Push CAPI_compile image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/thuai_compiler:latest
      - name: Push CAPI_runtime image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/thuai_client:latest
